### ISSUE TITLE
PyPI release and git tag

### ISSUE THREAD

**Issue by jakirkham** [TuragaLab/malis#4]
It would be nice for getting this into conda if we could have an official release of this package on PyPI. I would be happy to walk you through what needs to be done for this. Will probably need to do some more cleanup of the `setup.py` file first.

**Comment by jakirkham** [comment]
Seems there is a PyPI release. However, it has the version 0.0. Typically one picks a non-zero version. For instance, 0.1 would be a good choice to start. I encourage reading about [semver](http://semver.org/).

**Comment by srinituraga** [comment]
I think these issues have now been resolved. I hope I'm right? ;-)

**Comment by jakirkham** [comment]
At least half of it is (there appears to be a PyPI release). 😉 A git tag would still be nice.

**Comment by srinituraga** [comment]
Ah yes!

**Comment by grisaitis** [comment]
done 
https://github.com/TuragaLab/malis/tree/v1.0

**Comment by jakirkham** [comment]
Awesome. Thanks.
